# Generated by Django 5.1.1 on 2024-09-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('breed', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato')], max_length=255)),
                ('status', models.CharField(choices=[('adopted', 'Adoptado'), ('in adoption', 'En adopción'), ('awaiting adoption', 'En espera de adopción'), ('other', 'Otro')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'animals',
                'ordering': ['created_at'],
            },
        ),
    ]
